import Head from 'next/head'
import 'react-multi-carousel/lib/styles.css';
import { Inter } from 'next/font/google'
import  { Hero, Layout }  from '@components'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-slate-200'>
          <Layout>
            <Hero />
          </Layout>
      </main>
    </>
  )
}
